### ISSUE TITLE
Add ability to check entire list of items to be included in plugin

### ISSUE THREAD

**Issue by Marxsal** [TinkaPlugin/Tinka#14]
Currently you can specify a filter and then see a list of items to be included in the plugin. Great! But what if there are hundreds or thousands of items to be included (vocabulary items, book chapters, catalog entrees, etc.) ? It would be helpful if there was a way to say "mark all checkboxes" or to have the checkboxes marked by default. Thanks!

**Comment by TinkaPlugin** [comment]
Hi Marxsal,
thank you for suggesting this, I have added the ability to select/unselect all results of a search, hopefully it makes scenarios like these a little easier.

(See: 297428d74370c8559f2d820ae81794b3d1086ce2)
