### ISSUE TITLE
Add more visible link to github repository

### ISSUE THREAD

**Issue by twMat** [TinkaPlugin/Tinka#3]
Just a friendly proposal to include a link to this repository in the default tiddler 
I propose https://tinkaplugin.github.io/#Intro

Currently the link there only points to the site the visitor is already standing at.

**Comment by TinkaPlugin** [comment]
Thanks for the suggestion Mat, I totally agree and wonder why I didn't think of that already.
The recent update adds an appropriate link that makes navigating between the site and the repository much easier.


(Fixed in f8b532f2d64c16af3a69bd757d941231ca66ab25)
