### ISSUE TITLE
Search results are not linkified correctly

### ISSUE THREAD

**Issue by twMat** [TinkaPlugin/Tinka#4]
As seen, the titles are not linkified correctly. I guess there are some quotes or brackets missing.

![image](https://cloud.githubusercontent.com/assets/4534056/24588866/f121b5de-17d0-11e7-8992-db4095907b34.png)

**Comment by TinkaPlugin** [comment]
Thanks for reporting this Mat, I am now using the `<$text>` widget to display the text of the link so the wiki parser shouldn't mess up the search result links anymore.

(Fixed in f8b532f2d64c16af3a69bd757d941231ca66ab25)
