### ISSUE TITLE
Unable adding a 'Description' when creating a new plugin/theme

### ISSUE THREAD

**Issue by gernert** [TinkaPlugin/Tinka#5]
When creating a new plugin/theme there is no 'Description' field.
Only when repackaging you are able to fill in a 'Description'.

**Comment by TinkaPlugin** [comment]
Hi Ton,

you're right. This is especially true for themes, where this is a field that you would definitely want to set.
For normal plugins though, the `Plugin Title` field in the creation dialog actually just refers to the `description` field of the plugin to make it clear what it actually does. This might be confusing for some people who are more familiar with the plugin mechanism of TW, but my hope is that it also helps beginners get started.
 
For now, I have added a dedicated `description` field when creating themes, let me know if this is enough.

**Comment by gernert** [comment]
Hi Andreas,

An added description field for themes will be sufficient I think. See also my answer for #5.
