### ISSUE TITLE
Merge tab Installed into tab Create New

### ISSUE THREAD

**Issue by twMat** [TinkaPlugin/Tinka#7]
**Updated**: In my original proposal I had missed noting that one should use the listing under the Tinka "Installed" tab to re-make plugins. IMO this is easily missed and the following would be a superior and more streamlined UI:

I propose skipping the "Installed" tab all together and instead merge the re-make functionalities into into the "Create a new plugin" tab so this tab is really "Create or edit a plugin". The "Installed" tab is confusingly similar to the regular Controlpanel "Plugins" tab and it is IMO overall not quite clear what the "Installed" is for. Thus:

Instead of the current

![image](https://cloud.githubusercontent.com/assets/4534056/26736302/c8c2faec-47c5-11e7-8aa3-ef0f5ad3a877.png)

I propose a preliminary step like so

![image](https://cloud.githubusercontent.com/assets/4534056/26737151/41af6fd2-47c9-11e7-8f31-5f40bbbf5179.png)

...i.e you select what you intend to do and depending on selection you get the empty Create New form or the prepopulated form for existing tiddlers.

**Comment by TinkaPlugin** [comment]
I think the underlying issue to take a way here is that the "Installed" tab looks too much like the original plugin listing. If this wasn't the case, it would be more obvious that that is the place where one is supposed to edit a plugin.
Furthermore, the Help Tab functionality that encapsulates most common editing and quick-packaging scenarios is also hidden within the "Installed" section. Do you think changing the way the "Installed" section looks could already be enough in this instance?

**Comment by twMat** [comment]
>I think the underlying issue to take a way here is that the "Installed" tab looks too much like the original plugin listing. 

Maybe. But I think it is a poorer UI/UX with a separate Installed tab to begin with. And why should the user need a full plugin listing there anyway? What does the full *list* provide that the native Plugins list doesn't already? Just my opinion, of course. 

It is also the title of the tab; "Installed" doesn't in any way imply "re-package". 

Besides, the that listing suffers from the same UI problems that the native plugins list suffers e.g that the expand/collapse arrow button is weirdly placed to the left so it is not clear that it is a button. And the whole plugin thing is really a link (if anything, *that*, is what should be the expand/collapse button!) etc. 

>Furthermore, the Help Tab functionality that encapsulates most common editing and quick-packaging scenarios is also hidden within the "Installed" section. Do you think changing the way the "Installed" section looks could already be enough in this instance?

Oooh... I totally missed this! I was a bit confused by your email mentioning the Help Tab so I assumed you were talking about the *Documentation* link! Now I note the Help **button** that *triggers* a sidebar tab! Sorry, I had completely missed this.  Soo..., yes, I obviously agree is way too hidden, hehe!

But that sidebar Help Tab is also very confusing. Why should the user suddenly do stuff over there instead? It is a completely different interface.  Does it bring new functionality? I don't understand and it is quite possible that I'm missing something great.

**Comment by TinkaPlugin** [comment]
I have reworked the tab that was previously called "Installed", changed its name to "Modify plugins" and changed the selection and modification process to what was outlined in your wonderful picture above. Thanks Mat!
