### ISSUE TITLE
In the meta-data table, remove superfluous "Name" field

### ISSUE THREAD

**Issue by twMat** [TinkaPlugin/Tinka#9]
In the meta-data, before selecting "plugin" or "theme", which is mandatory to do, there is a **name** field (next to the *Description* field) which does not contribute anything. It disappears as soon an one selects plugin or theme. Actually, the Description field is apparently transformed into the "Plugin title" field.

Considering how it is useful with a description, I propose to keep both fields also after the plugin/theme selection is done. 

When the plugin is packaged, those two fields are merged into `<name> - <descrition>` to get e.g "Tinka - an easy plugin packer"

**Comment by TinkaPlugin** [comment]
For plugins the `description` field of the plugin specifies the text that is presented in the control panel, which is the apparent 'title' of the plugin for a user.

For themes however, the `name` field is whats being used by TW to display a sort of 'title' for the theme, therefore when selecting the plugin type, either one or the other transforms into "Theme/Plugin title" to make it apparent what the field is for. If you are creating a bundle that is neither of type 'plugin' nor of type 'theme', I imagine it will still be useful to be able to set the name and description field separately.

As far as I know, you are still able to set a description with a theme, which will be presented as a subtitle in the plugin view. So the way TW handles the `description` and `name` fields differently for themes and plugins directly determines how Tinka chooses to display them.

So Tinka is already doing confusing "black magic" tricks to make sure that creating plugins is consistent, easy and understandable, so I am not sure if further detaching it from how TW works makes more sense, I'll need to think about this some more. Ideally though TW would deal with the `name` and `description` field consistently, so Tinka didn't have to do this.

Also refer to #5 and #6 which also boil down to the same issue.

**Comment by twMat** [comment]
I probably misunderstand something but: If there are two fields all the time...

`Name: [ e.g Tinka ]` and `Description: [ e.g "a simple plugin packer" ]` 

...for **all** bundling cases, then the various bundlings can use them as is appropriate.

This contradicts the OP, but after you reply above I understand both fields are needed so hopefully this is a solution instead.

**Comment by TinkaPlugin** [comment]
Hi Mat,
with recent changes in TiddlyWiki5, I am happy to report that this is now more consistent and Tinka now displays them accordingly.
